server:
 port: ${SERVER_PORT}

spring:
  application:
    name: bff-agendador
api:
  usuario:
    url: ${USUARIO_SERVICE_URL}
  tarefa:
    url: ${AGENDADOR_SERVICE_URL}
  notificacao:
    url: ${NOTIFICACAO_SERVICE_URL}
  comunicacao:
    url: ${COMUNICACAO_SERVICE_URL}
usuario:
  email: noreply.agendador.dev@gmail.com
  senha: admin
cron:
  horario: 0 0/5 * * * ?